baseURL = 'https://penserbjorne.com/'
languageCode = 'es-mx'
title = 'Penserbjorne'
theme = 'hugo-cat'
PygmentsCodeFences = true
PygmentsStyle = "solarized-dark256"
pluralizelisttitles = "false"
paginate  = 15
disableHugoGeneratorInject = false
enableEmoji = true

[params]
ava = "/img/penserbjorne_400x400.jpg"
owner ="Paul Aguilar (Æsahættr Penserbjorne)"
talk = "Hola Mundo &#128075;!"
blogSection = ["blog"]
description = "Sitio web de Paul Aguilar (Æsahættr Penserbjorne)"
favicon = "/img/logo-daemon-emoji.svg"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 2

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 3

[[menu.main]]
name = "About"
url = "/about/"
weight = 4



[module]
  [module.hugoVersion]
    extended = true
    min = "0.111.3"

